kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-volume-person
  labels:
    type: local
    app: postgres-person
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/db-person"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc-person
  labels:
    app: postgres-person
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-srv-person
  labels:
    app: db-person
spec:
  type: NodePort
  selector:
    app: db-person
  ports:
   - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dep-person
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-person
  template:
    metadata:
      labels:
        app: db-person
    spec:
      containers:
        - name: postgres-container-person
          image: postgis/postgis:12-2.5-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-person
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-person
                key: DB_NAME
          volumeMounts:
            - mountPath: /var/lib/db-person/data
              name: db-person
      volumes:
        - name: db-person
          persistentVolumeClaim:
            claimName: postgres-pvc-person
