kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-volume-connection
  labels:
    type: local
    app: db-connection
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/db-connection"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc-connection
  labels:
    app: db-person
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-srv-connection
  labels:
    app: db-connection
spec:
  type: NodePort
  selector:
    app: db-connection
  ports:
   - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dep-connection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-connection
  template:
    metadata:
      labels:
        app: db-connection
    spec:
      containers:
        - name: postgres-container-person
          image: library/postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-connection
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-connection
                key: DB_NAME
          volumeMounts:
            - mountPath: /var/lib/db-connection/data
              name: db-connection
      volumes:
        - name: db-connection
          persistentVolumeClaim:
            claimName: postgres-pvc-connection
