kind: PersistentVolume
apiVersion: v1
metadata:
  name: connections-postgres-volume
  labels:
    type: local
    app: connection-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/connectiondb"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-connection-pv-claim
  labels:
    app: connection-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: connection-postgres
  labels:
    app: connection-postgres
spec:
  type: NodePort
  selector:
    app: connection-postgres
  ports:
   - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connection-postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connection-postgres
  template:
    metadata:
      labels:
        app: connection-postgres
    spec:
      containers:
        - name: connection-postgres
          image: postgis/postgis:12-2.5-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-connection
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-connection
                key: DB_NAME
          volumeMounts:
            - mountPath: /var/lib/connection-postgresql/data
              name: connection-postgresdb
      volumes:
        - name: connection-postgresdb
          persistentVolumeClaim:
            claimName: postgres-connection-pv-claim
