name: UdaConnect - Package with Docker

# Controls when the action will run. 
on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: modules/person-microservice
          platforms: linux/amd64
          push: true
          tags: fadyrefaat/cn-nd-person-api:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: modules/connection-microservice
          platforms: linux/amd64
          push: true
          tags: fadyrefaat/cn-nd-connection-api:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: modules/location-microservice
          platforms: linux/amd64
          push: true
          tags: fadyrefaat/cn-nd-location-api:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: modules/location-consumer
          platforms: linux/amd64
          push: true
          tags: fadyrefaat/cn-nd-location-consumer:latest

